### ISSUE TITLE
Prefer `button` to `a` for Toggle Behaviors

### ISSUE THREAD

**Issue by nbibler** [HaulinOats/todo-app#7]
Unless you're navigating a user to some other page, don't use an anchor tag. There's probably a better option (likely a `button`).

The easy way to tell, is if you don't have an href value (a place to send someone), you probably shouldn't use an anchor tag.

https://github.com/HaulinOats/todo-app/blob/9eb0ce07afc81361417f443b4872c7c6a3b47016/components/TodoList.tsx#L146

Instead something like (although I'm sure there will be some styling changes necessary to support it):

```tsx
<li className={todoView === "all" ? styles.active_filter_view : ""}>
  <button type="button" onClick={() => setTodoView("all")}>
    All
  </button>
</li>
```

Better still, and I know you had questions about the ternary class names earlier, if you're willing to take the dependency, [`classnames`](https://www.npmjs.com/package/classnames) provides a nice interface. It allows you to define a list of static class names, but then also an object where the keys are the class names and the values are the dynamic conditional (truthy = use this key). It's less clear here where there's only 1 dynamic class name, but becomes very apparent when you might have 3 or 4 on a single element.

```typescript
import classnames from 'classnames';

//…

<li className={classnames({ [styles.active_filter_view]: todoView === "all" })}>
  <button type="button" onClick={() => setTodoView("all")}>
    All
  </button>
</li>
```

**Comment by HaulinOats** [comment]
I went with anchor elements because that's what the TodoMVC app was doing (wasn't sure if I would have been penalized for not following explicit directions) and also because I was trying earlier today to get those links working via hash routes (If you click on the [filter links](https://todomvc.com/examples/typescript-react/#/) in the reference app you can see what I was trying to emulate). I'm not an SEO expert but I normally try to write HTML that makes some kind of structural sense as I know just making everything a div or span isn't best practice. Just wanted you to be aware that I went with anchors in this scenario due to trying my best to mimic the reference app. 

`classnames` seems super useful. I find inline ternary to be super ugly but feels like a necessary evil sometimes. This package looks like a nicer way of handling that. I'll add it.
